
services:
  alpine-python-flask-hl:
    build: .
    image: hackinglab/alpine-python-flask-hl:3.2
    environment:
    - AUTHOR=e1
    - HL_USER_USERNAME=hacker
    - GOLDNUGGET=FLAG{hl-smoke-test}
    ports:
      - 80:8080


